# Generated by Django 4.2 on 2024-07-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('hores_dedicacio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAprenentatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.TextField()),
                ('hores', models.PositiveIntegerField()),
                ('assignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_aprenentatge', to='assignatures.assignatura')),
            ],
        ),
    ]
