# Generated by Django 4.2 on 2024-07-02 15:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignatura',
            name='data_inici',
            field=models.DateField(default=datetime.datetime(2024,9,1)),
            preserve_default=False,
        ),
    ]
